import Head from 'next/head'
import Navbar from '../components/Navbar'
import Welcome from '../components/Welcome'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div className='main-page'>
        <div className='position-fixed'>

        </div>
        <div className='nav-mid-contaner'>
          <Welcome />
          
        </div>
        <div className='position-fixed'>

        </div>
      </div>
    </div>
  )
}
